apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb.yaml
  - rabbitmq.yaml
  - order-service.yaml
  - product-service.yaml
  - makeline-service.yaml
  - store-front.yaml
  - store-admin.yaml
  - virtual-customer.yaml
  - virtual-worker.yaml

commonLabels:
  app.kubernetes.io/part-of: aks-store-demo
